---
- name: working with special cases
  hosts: all
  tasks:
      - name: gather server ipaddress & name
        shell: "uptime; uname -a"

      - name: gather ipaddress
        shell: "hostname -i"
        delegate_to: "Node-1" 